#!/usr/bin/env fish

function main
    # ## Config
    set -l PROG_NAME    "Phalcon PHP Framework"
    set -l USERNAME     $USER
    set -l TMPLOC       "/tmp/phalcon"
    set -l TAG          "1.3.4"
    
    # check if phalcon is installed and if is the same version
    set -l PHALCON_VER (php -r "echo phpversion('phalcon');")
    
    if test -n $PHALCON_VER
        if test $TAG = $PHALCON_VER
            echo "
    A previous $PROG_NAME version $TAG installation is detected.
    "
      echo "Req Error: Already installed" >&2
      exit 84
        end
    end
    
    # ## Install dependencies
    sudo apt-get install php5-dev libpcre3-dev gcc make
    or begin
      set -l err $status
      echo "Error: Failure installing $PROG_NAME dependencies"
      echo "Error: apt-get failed to install dependencies" >&2
      exit $err
    end
    
    # ## Download Phalcon from github
    sudo mkdir -p "$TMPLOC"
    and pushd $TMPLOC
    and sudo git clone https://github.com/phalcon/cphalcon.git -b $TAG
    or begin
      set -l err $status
      echo "Error $err: Failed to download $PROG_NAME Version '$TAG'"
      exit $err
    end
    
    pushd cphalcon/build/64bits/
    
    echo "Configuring Phalcon."
    sudo phpize -clean
    or begin
      set -l err $status
      echo "Error $err:"
      exit $err
    end
    
    sudo ./configure --enable-phalcon
    or begin
      set -l err $status
      echo "Error $err:"
      exit $err
    end
    
    # Install PhalconPHP
    echo "Compiling Phalcon."
    sudo make install
    or begin
      set -l err $status
      echo "Error $err:"
      exit $err
    end
    
    # Configuring the phalcon.ini
    echo 'extension=phalcon.so' | sudo tee /etc/php5/mods-available/phalcon.ini > /dev/null
    for directory in apache2 cli cgi fpm;
        if test -d /etc/php5/$directory/
            if test ! -L /etc/php5/$directory/conf.d/30-phalcon.ini
                sudo ln -s /etc/php5/mods-available/phalcon.ini /etc/php5/$directory/conf.d/30-phalcon.ini
            end
        end
    end
    
    # ## Cleanup
    sudo rm -rf "$TMPLOC"
    
    set -l downloadedVer (php -r "echo phpversion('phalcon');")
    echo "
    $PROG_NAME $downloadedVer installation is complete.
    "
    
    # ## Reboot Apache
    sudo service apache2 restart
    or begin
      set -l err $status
      echo "Error: Apache failed to restart"
      echo "Error: Apache failed to restart" >&2
      exit $err
    end

end

main
# vim: set filetype=fish: