#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "pip"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not which pip > /dev/null
  echo "
An installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 1
end



# ## Uninstall
sudo apt-get purge -y python-pip
or begin
  set -l err $status
  echo "Error: Failed to uninstall $PROG_NAME"
  echo "Error: apt-get purge failed" >&2
  exit $err
end



# ## Autoremove
sudo apt-get -y autoremove
or begin
  set -l err $status
  echo "Error: Failed to cleanup after $PROG_NAME"
  echo "Error: apt-get autoremove failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
