#!/usr/bin/env fish
function main



# ## Config
set -l PROG_NAME    "Rails"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not which rails > /dev/null
  echo "
A $PROG_NAME installation cannot be found.
"
  echo "Req Error: Cannot find install" >&2
  exit 1
end



# ## Uninstall
sudo gem uninstall rails
or begin
  set -l err $status
  echo "Error: Failure uninstalling rails"
  echo "Error: gem uninstall failed" >&2
  exit $err
end



# ## Purge some dependencies
# Note that we're not purging all dependencies, since some things
# (like build-essentials) *may* be required by other programs. We're
# only removing what we're resonable sure that isn't required.
sudo apt-get purge -y ruby-dev libsqlite3-dev
or begin
  set -l err $status
  echo "Error: Failure installing dependencies"
  echo "Error: apt-get install failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
