#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Tomcat7"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not test -e /var/lib/tomcat7
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
end



# ## Uninstall
sudo apt-get purge --auto-remove -y tomcat7 \
  tomcat7-docs tomcat7-admin tomcat7-examples
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: apt-get failed to uninstall" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
