#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "pgcli"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not which pgcli > /dev/null
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 1
end



# ## Uninstall
sudo pip uninstall -y pgcli
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: pip failed to uninstall" >&2
  exit $err
end



# ## Uninstall Dependencies
sudo apt-get purge --auto-remove -y python-dev libpq-dev libevent-dev
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME dependencies"
  echo "Error: apt-get failed to uninstall dependencies" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
