#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Linux Dash"
set -l USERNAME     $USER
set -l INSTLOC      ~/Web/linux-dash



# ## Check Requirements
# ### Check if installed
if not test -e "$INSTLOC"
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 1
end



# ## Uninstall
rm -rf "$INSTLOC"
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: Failed to remove $PROG_NAME" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
