#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Google Drive"
set -l REQ_STORAGE  100
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if which grive < /dev/null
  echo "
$PROG_NAME is already installed. To synchronize your file system with
your Google Drive, run the following command:

    \$ cd ~/GDrive
    \$ grive
"
  echo "Req Error: Already installed" >&2
  exit 84
end
# ### User not root
if test "$USERNAME" = "root"
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Not logged in as user" >&2
  exit 84
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 84
end



# This message is here due to a pause on apt-get update that might
# confuse the user. A vague message will help them know that it isn't
# froze.
echo -e "\nUpdating.."



# ## Update
sudo apt-get update
or begin
  set -l err $status
  echo "Error: Failed to update package list"
  echo "Error: apt-get update failed" >&2
  exit $err
end



# ## Install
sudo apt-get install -y grive
or begin
  set -l err $status
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: apt-get failed to install $PROG_NAME" >&2
  exit $err
end



# ## Symlink
# I'm not positive if this is still required. We have it listed in the
# Koding learn guide.
#sudo ln -s /usr/lib/libbfd-2.23.2-system.so /usr/lib/libbfd-2.23-system.so
#or begin
#  set -l err $status
#  echo "Error: Failed to link system library"
#  echo "Error: Failed to symlink /usr/lib/libbfd-2.23.2-system.so" >&2
#  exit $err
#end



# ## Make GDrive
# No reason to check for failure, -p can't fail (i believe)
mkdir -p ~/GDrive



# ## Success
echo "
$PROG_NAME installation complete. Next you need to authorize
the $PROG_NAME CLI with Google services. To do this, type the following
command:

    \$ cd ~/GDrive
    \$ grive -a

After you are authorized, run:

    \$ grive

To synchronize your file system with your Google Drive.
"
end
main
# vim: set filetype=fish:

