#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Elasticsearch"
set -l REQ_STORAGE  29136
set -l USERNAME     $USER
set -l DEBIAN       "elasticsearch-1.4.2.deb"



# ## Check Requirements
# ### Already installed?
if test -e /etc/elasticsearch
  echo "
A previous $PROG_NAME installation is detected. The API is accessible
from the following URL:

    $USERNAME.koding.io:9200
"
  echo "Req Error: Already installed" >&2
  exit 84
end
# ### Oracle Java7 Installed?
java -version 2>| grep -iq "se runtime"
and java -version 2>| grep -iq "1.7"
or begin
  echo "
$PROG_NAME requires Oracle Java7 to be installed. You can install it
with the following command:

    \$ kpm install oracle-java7
"
  echo "Req Error: Installation not found" >&2
  exit 84
end
# ### User not root
if test "$USERNAME" = "root"
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Not logged in as user" >&2
  exit 84
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 84
end



# ## Download
sudo curl -L -o "/tmp/$DEBIAN" \
  "https://download.elasticsearch.org/elasticsearch/elasticsearch/$DEBIAN"
or begin
  set -l err $status
  echo "Error: Failed to download $PROG_NAME"
  echo "Error: Downloading deb from elasticsearch.org failed" >&2
  exit $err
end



# ## Install Deb
sudo dpkg -i "/tmp/$DEBIAN"
or begin
  set -l err $status
  echo "Error: Failed to install $PROG_NAME"
  echo "Error: dpki -i failed" >&2
  exit $err
end



# ## Configure startup
# Set elasticsearch to auto-start, and start it
sudo update-rc.d elasticsearch defaults 95 10
and sudo service elasticsearch start
or begin
  set -l err $status
  echo "Error: Failure to configure and start $PROG_NAME"
  echo "Error: Setting auto-start and starting ES failed" >&2
  exit $err
end



# ## Cleanup temp file
sudo rm "/tmp/$DEBIAN"
or begin
  set -l err $status
  echo "Warning: Failed to cleanup temp file"
  echo "Warning: Failed to cleanup Deb file in temp dir" >&2
  # Don't exit for warnings
end



# ## Success
echo "
$PROG_NAME installation complete. The API is accessible from the
following URL:

    $USERNAME.koding.io:9200
"
end
main
# vim: set filetype=fish:
