#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Elasticsearch"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not test -e /etc/elasticsearch
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 1
end



# ## Uninstall Deb
sudo dpkg --purge elasticsearch
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: dpkg failed to uninstall" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
