#!/usr/bin/env fish
function main



# ## Config
set -l PROG_NAME    "Codeigniter"
set -l USERNAME     $USER
set -l INSTALL_LOC  ~/Web/codeigniter



# ## Check Requirements
# ### Is it installed?
if not test -e "$INSTALL_LOC"
  echo "Error: A $PROG_NAME installation in the default kpm install
location cannot be found."
  echo "Req Error: Cannot find install" >&2
  exit 84
end



# ## Confirm
echo "
By uninstalling $PROG_NAME, you will FULLY DELETE the kpm installation of
$PROG_NAME. This includes any data found within the following directory.

    $INSTALL_LOC

This cannot be undone.

Are you sure?
"
for x in (seq 3)
  echo -n "(yes/no, y/n) "
  read -l confirm < /dev/tty
  or begin
    echo "Input Error: Empty confirm response" >&2
    exit 1
  end
  switch "$confirm"
    case "yes" "y" "Y" "Yes" "YES"
      break
    case "no" "n" "N" "No" "NO"
      echo "Confirm choice no" >&2
      exit 1
    case "*"
      if test "$x" -eq 3
        echo -e "\nAborting after 3 failed attempts"
        exit 1
      else
        echo -e "\nInvalid response, please retry."
      end
  end
end



# ## Remove
rm -rf $INSTALL_LOC
# I don't think it's possible for `rm -rf` to return a non-zero



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
