#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Nginx"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not which nginx > /dev/null
  echo "
An installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
end



# ## Uninstall
sudo apt-get purge --auto-remove -y nginx
or begin
  set -l err $status
  echo "Error: Failed to uninstall $PROG_NAME"
  echo "Error: apt-get purge failed" >&2
  exit $err
end



# ## Start apache2
# We don't care about errors, because we can't be sure that Apache
# was properly setup. Nevertheless, warn the user if anything fishy
# happens.
sudo service apache2 restart
or begin
  set -l err $status
  echo "Warning: Failed to restart Apache"
  echo "Warning: service failed to restart Apache" >&2
  # Don't exit, only a warning not an error
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
