#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Memcached"
set -l REQ_STORAGE  316
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if which memcached > /dev/null
  echo "
$PROG_NAME is already installed. If you need to start it, run the
following command:

  \$ sudo service memcached start
"
  echo "Req Error: Already installed" >&2
  exit 1
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 1
end



# ## Install
sudo apt-get install -y memcached
or begin
  set -l err $status
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: apt-get failed to install $PROG_NAME" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME installation complete, and the $PROG_NAME server is running.
"
end
main
# vim: set filetype=fish:

