#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Nginx"
set -l REQ_STORAGE  2116
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if which nginx > /dev/null
  echo "
$PROG_NAME is already installed.
"
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

"
  echo "Req Error: Not enough storage" >&2
  exit 1
end



# ## Install
sudo apt-get install -y nginx
or begin
  set -l err $status
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: apt-get install failed" >&2
  exit $err
end



# Configure
set -l orig "\troot \/usr\/share\/nginx\/html;"
set -l repl "\troot \/var\/www;"
sudo sed -i -e "s/$orig/$repl/g" /etc/nginx/sites-available/default



# ## Stop apache
# Shouldn't need to error check here, we don't really care about Apache,
# it's just running by default.
sudo service apache2 stop



# ## Start nginx
sudo service nginx restart
or begin
  set -l err $status
  echo "Error: $PROG_NAME failed to restart"
  echo "Error: service failed to restart $PROG_NAME" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME installation complete and your Web directory is being
served by $PROG_NAME
"
end
main
# vim: set filetype=fish:

