#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "novnc"
set -l REQ_STORAGE  13048
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if test -e /usr/share/kpmnovnc
  echo "
$PROG_NAME is already installed. If you need to start it, run the
following command:

  \$ novnc
"
  echo "Req Error: Already installed" >&2
  exit 1
end
# ### tightvnc installed?
if which vncserver > /dev/null
  echo "
The kpm installation of $PROG_NAME requires that VNC is already installed.
Please install it with the following command:

  \$ kpm install vnc
"
  echo "Req Error: Apache not installed" >&2
  exit 1
end
# ### User not root
if test "$USERNAME" = "root"
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Not logged in as user" >&2
  exit 1
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 1
end



# ## Download
sudo git clone https://github.com/kanaka/noVNC /usr/share/kpmnovnc > /dev/null
or begin
  set -l err $status
  echo "Error: Failure downloading $PROG_NAME"
  echo "Error: git clone failed $PROG_NAME" >&2
  exit $err
end



# ## Hack novnc hostname
# Koding VMs by default don't have a "proper" hostname, and novnc's
# launch script uses hostname to print the default novnc address.
# This is likely to confuse users, so we're replacing the hostname
# usage found here:
#
#     https://github.com/kanaka/noVNC/blob/master/utils/launch.sh#L115
#
# With a static url of the user's default domain.
sudo sed -i -e "s/\$(hostname)/$USERNAME.koding.io/g" /usr/share/kpmnovnc/utils/launch.sh




# ## Add beginner friendly shortcut script
# Note that we're piping to null to hide tee's stdout echo
echo "
#!/usr/local/env fish
cd /usr/share/kpmnovnc
sudo -u $USERNAME ./utils/launch.sh --vnc localhost:5901
" | sudo tee /usr/local/bin/novnc > /dev/null
sudo chmod +x /usr/local/bin/novnc



# ## Success
echo "
$PROG_NAME installation complete. To start a noVNC Session, run the
following shortcut command:

  \$ novnc
"
end
main
# vim: set filetype=fish:

