#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "pip"
set -l REQ_STORAGE  48740
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if which pip > /dev/null
  echo "
$PROG_NAME is already installed. You can access it by running the
following command:

    \$ pip

"
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 1
end



# ## Install
sudo apt-get install -y python-pip
or begin
  set -l err $status
  echo "Error: Failure installing pip"
  echo "Error: apt-get install failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME installation complete. To access it, run the following
command:

    \$ pip

"
end
main
# vim: set filetype=fish:

