#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Redis"
set -l REQ_STORAGE  1664
set -l USERNAME     $USER



# ## Check Requirements
# ### Already installed?
if which redis-server > /dev/null
  echo "
$PROG_NAME is already installed. If it is not running, you can start it
by running the following command:

    \$ sudo service redis-server start

Or connect to the client, with the following command:

    \$ redis-cli

"
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url:

    https://koding.com/Pricing

"
  # Add this message to the above echo, once the guide exists
  #Please refer to the following guide to learn how to list and remove unused packages.
  echo "Req Error: Not enough storage" >&2
  exit 1
end



# ## Install
sudo apt-get install -y redis-server
or begin
  set -l err $status
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: apt-get install failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME installation complete. You can connect to the client with
the following command:

    \$ redis-cli

"
end
main
# vim: set filetype=fish:

