#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Ungit"
set -l REQ_STORAGE  108328
set -l USERNAME     $USER


# ## Check Requirements
# ### User not root
# Ensure that the user is not `root`, because the default Apache
# web directory is /home/user/Web, where as root would
# install it to /root/Web
if test "$USERNAME" = "root"
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Logged in as root" >&2
  exit 84
end
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  echo "
$PROG_NAME requires at least "(math $REQ_STORAGE / 1024)"MB storage, \
and you have "(math $available_storage / 1024)"MB free.

Please free up some space, and try again. You can start by deleting any large
files or directories in your home directory or delete software that you do
not need.

You can also upgrade your account to get more space, at the following url

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  # Add this message to the above echo, once the guide exists
  #Please refer to the following guide to learn how to list and remove unused packages.
  echo "Req Error: Not enough storage" >&2
  exit 84
end
# ### Check if node is installed
if not which node > /dev/null
  echo "
$PROG_NAME requires that NodeJS is already installed. Please
install it first.
"
  echo "Req Error: Missing nodejs" >&2
  exit 84
end
# ### Check if npm are installed
if not which npm > /dev/null
  echo "
$PROG_NAME requires that NPM is already installed. Please
install it first.
"
  echo "Req Error: Missing npm" >&2
  exit 84
end
# ### Check if already installed
if which ungit > /dev/null
  echo "
$PROG_NAME is already installed. It can be started with the following \
command:

    \$ ungit

You can access your $PROG_NAME installation at the following address:

    $USERNAME.koding.io:8448
"
  echo "Req Error: Already installed" >&2
  exit 84
end



# ## Install
echo "
Installing $PROG_NAME
"
sudo -H npm install -g ungit
or begin
  set -l err $status
  echo "Error: Failure installing ungit"
  echo "Error: Failure installing ungit" >&2
  exit $err
end



# ## Start
#ungit --port 8448 > /dev/null &
#or begin
#  set -l err $status
#  echo "Error: Starting installing ungit"
#  echo "Error: Starting installing ungit" >&2
#  exit $err
#end



# ## End
echo "
Installation complete. To start $PROG_NAME run the following command:

    \$ ungit

You can access $PROG_NAME at the following address:

    $USERNAME.koding.io:8448
"
end
main
# vim: set filetype=fish:
