#!/usr/bin/env fish
function main


# ## Config
set -l PROG_NAME    "Ungit"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not which ungit > /dev/null
  echo "
A $PROG_NAME installation cannot be found.
"
  echo "Req Error: Cannot find install" >&2
  exit 84
end



# ## Uninstall Ungit
sudo -H npm uninstall -g ungit
or begin
  set -l err $status
  echo "Error: Failed to uninstall $PROG_NAME"
  echo "Error: npm uninstall -g ungit failed" >&2
  exit $err
end



# ## Clean npm cache
# In an effort to trim valuable user storage, we're cleaning
# the npm cache since it soaks up around ~60mb for the ungit
# install alone.
sudo -H npm cache clean
or begin
  set -l err $status
  echo "Error: Failed to clear cache $PROG_NAME"
  echo "Error: npm cache clean failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"



end
main
# vim: set filetype=fish:
