#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Django"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if already installed
if not which django-admin > /dev/null
  echo "
An installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
end
# ### Uninstall requirement
if not which pip > /dev/null
  echo "
To uninstall Django properly, please install pip with the following
command:

    \$ kpm install pip

"
  echo "Req Error: pip not found" >&2
  exit 84
end



# ## Uninstall
sudo pip uninstall -y django
or begin
  set -l err $status
  echo "Error: Failed to uninstall $PROG_NAME"
  echo "Error: pip uninstall failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
