#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "phpPgAdmin"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not test -e /usr/share/phppgadmin
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 1
end



# ## Uninstall
sudo apt-get purge --auto-remove -y phppgadmin
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: apt-get failed to uninstall" >&2
  exit $err
end



# ## Remove softlinked
sudo rm /var/www/phppgadmin
or begin
  set -l err $status
  echo "Error: Failed to remove softlink"
  echo "Error: Failed to remove /var/www/phppgadmin" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
