#!/bin/bash

# Config
PROG_NAME="Jekyll"
REQ_STORAGE=237000
USERNAME=$USER


# Check if it's installed
if [ $(which jekyll) > /dev/null ]; then
  echo "
$PROG_NAME is already installed. If you need to start it, run the
following command:

  \$ jekyll new ~/JekyllSite
  \$ cd ~/JekyllSite
  \$ jekyll serve --host 0.0.0.0

Then navigate to:

    http://$USERNAME.koding.io:4000
"
  echo "Req Error: Already installed" >&2
  exit 84
fi


# Check if the user is `root`
if [ $USERNAME == "root" ]; then
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Logged in as root" >&2
  exit 84
fi


# Check if there's not enough storage
available_storage=$(df / | awk 'NR>1{print $4}')

if (($available_storage < $REQ_STORAGE)); then
  echo "
$PROG_NAME requires at least "$(expr $REQ_STORAGE / 1024)"MB storage, \
and you have "$(expr $available_storage / 1024)"MB free.

Please free up some space, and try again. You can start by deleting any large
files or directories in your home directory or delete software that you do
not need.

You can also upgrade your account to get more space, at the following url

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 84
fi


# Download RVM and Jekyll
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --ruby
source .rvm/scripts/rvm
gem install jekyll
