#!/bin/bash
function main() {

# ## Config
PROG_NAME="Jekyll"
REQ_STORAGE=237000
USERNAME=$USER


# ## Check if it's installed
if [ $(which jekyll) > /dev/null ]; then
  echo "
$PROG_NAME is already installed. If you need to start it, run the
following command:

  \$ jekyll new ~/JekyllSite
  \$ cd ~/JekyllSite
  \$ jekyll serve --host 0.0.0.0

Then navigate to:

    http://$USERNAME.koding.io:4000
"
  echo "Req Error: Already installed" >&2
  exit 84
fi


# ## Check if the user is `root`
if [ $USERNAME == "root" ]; then
  echo "
$PROG_NAME should not be installed from the root user. Please switch
to your normal Koding user, and try this command again.
"
  echo "Req Error: Logged in as root" >&2
  exit 84
fi


# ## Check if gem is installed
# Note that we don't require ruby2, but at the time of writing this
# script there is no plain ruby installer, just ruby2.
if ! which gem >/dev/null; then
  cat << EOF

The kpm version of $PROG_NAME requires that Ruby & Gem are already
installed.  Please install it with the following command:

    \$ kpm install ruby2

EOF
  echo "Req Error: Missing gem" >&2
  exit 84
fi


# ## Check if there's not enough storage
available_storage=$(df / | awk 'NR>1{print $4}')
if (($available_storage < $REQ_STORAGE)); then
  echo "
$PROG_NAME requires at least "$(expr $REQ_STORAGE / 1024)"MB storage, \
and you have "$(expr $available_storage / 1024)"MB free.

Please free up some space, and try again. You can start by deleting any large
files or directories in your home directory or delete software that you do
not need.

You can also upgrade your account to get more space, at the following url

    https://koding.com/Pricing

Please refer to the following guide for tips on how to free up VM storage:

    http://learn.koding.com/guides/freeing-up-space
"
  echo "Req Error: Not enough storage" >&2
  exit 84
fi



# ## Update
# This message is here due to a pause on apt-get update that might
# confuse the user. A vague message will help them know that it isn't
# froze.
echo "Updating.."
sudo apt-get update
err=$?; if [ "$err" -ne 0 ]; then
  echo "Error: Failed to update package list"
  echo "Error: apt-get update failed" >&2
  exit $err
fi



# ## Install
sudo apt-get install -y make
err=$?; if [ "$err" -ne 0 ]; then
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: apt-get failed to install" >&2
  exit $err
fi


# ## Install jekyll
sudo gem install jekyll
err=$?; if [ "$err" -ne 0 ]; then
  echo "Error: Failed to install jekyll"
  echo "Error: gem failed to install jekyll" >&2
  exit $err
fi


# ## Success
cat << EOF

$PROG_NAME installation complete. To create a new $PROG_NAME server and
start it, run the following commands:

  \$ jekyll new JekyllSite
  \$ cd JekyllSite
  \$ jekyll serve --host 0.0.0.0

EOF

}
main
