#!/bin/bash
function main() {

# Config
PROG_NAME="Jekyll"
USERNAME=$USER

# Check if it's installed
if ! [ $(which jekyll) > /dev/null ]; then
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
fi

# Remove RVM & Jekyll
sudo gem uninstall jekyll
err=$?; if [ "$err" -ne 0 ]; then
  echo "Error: Failed to remove jekyll"
  echo "Error: Gem failed to remove jekyll"
  exit $err
fi

# Success
echo "
$PROG_NAME has been uninstalled successfully.
"

}
main
