#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Composer"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
if not test -e /usr/local/bin/composer
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
end



# ## Remove configs and packages
# No point in error checking on -rf
sudo rm -rf ~/.composer



# ## Uninstall bin
sudo rm /usr/local/bin/composer
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME bin"
  echo "Error: rm bin failed" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
