#!/usr/bin/env fish
function main
# ## Config
set -l PROG_NAME    "Oracle Java7"
set -l USERNAME     $USER



# ## Check Requirements
# ### Check if installed
java -version 2>| grep -iq "se runtime"
and java -version 2>| grep -iq "1.7"
or begin
  echo "
A kpm installation of $PROG_NAME cannot be found.
"
  echo "Req Error: Installation not found" >&2
  exit 84
end



# ## Uninstall
sudo apt-get purge --auto-remove -y "oracle-java7*" "oracle-jdk7*"
or begin
  set -l err $status
  echo "Error: Failed to remove $PROG_NAME"
  echo "Error: apt-get failed to uninstall" >&2
  exit $err
end



# ## Remove key
sudo add-apt-repository --remove -y ppa:webupd8team/java
and sudo apt-get update
or begin
  set -l err $status
  echo "Error: Failed to remove Oracle repository"
  echo "Error: Removing and updating with ppa:webupd8team/java" >&2
  exit $err
end



# ## Success
echo "
$PROG_NAME has been uninstalled successfully.
"
end
main
# vim: set filetype=fish:
