#!/usr/bin/env fish
function main

# ## Config
set -l PROG_NAME    "Mean"
set -l REQ_STORAGE  120508
set -l USERNAME     $USER

# ## Check Requirements
# ### Storage
set -l available_storage (df / | awk 'NR>1{print $4}')
if test (math $available_storage - $REQ_STORAGE) -lt 0
  set -l hReq (math $REQ_STORAGE / 1024)
  set -l hAvl (math $available_storage / 1024)
  echo "
$PROG_NAME requires at least $hReq""MB storage, \
and you have $hAvl""MB free.

Please free up some space, and try again. You can start by deleting any
large files or directories in your home directory or delete software that
you do not need.

You can also upgrade your account to get more space, at the following url

    https://koding.com/Pricing
"
  echo "Req Error: Not enough storage" >&2
  exit 84
end

# ### Check if already installed
if which mean > /dev/null
  echo "
$PROG_NAME is already installed. It can be started with the following \
command:

    \$ mean myApp
"
  echo "Req Error: Already installed" >&2
  exit 84
end

# ### Check if node is installed
if not which node > /dev/null
  echo "
$PROG_NAME requires that NodeJS is already installed. Please
install it first.
"
  echo "Req Error: Missing npm" >&2
  exit 84
end

# ## Check if npm installed
if not which npm > /dev/null
  echo "
$PROG_NAME requires that npm is already installed. Please install
npm first.
"
  echo "Req Error: Missing npm" >&2
  exit 84
end

# ## Check if mongodb installed
if not which mongo > /dev/null
  echo "
$PROG_NAME requires that mongodb is already installed. Please install
mongo first.
"
  echo "Req Error: Missing mongodb" >&2
  exit 84
end


# ## Check if Grunt installed
if not which grunt > /dev/null
  echo "
$PROG_NAME requires that grunt is already installed. Please install
grunt first.
"
  echo "Req Error: Missing grunt" >&2
  exit 84
end



# ## Install
# ### build-essential - These will be needed for the user to npm install a mean project without getting bson errors
sudo apt-get install -y gcc make build-essential
or begin
  set -l err $status
  echo "Error: Failure installing apt dependencies"
  echo "Error: Failure installing gcc, make, build-essential" >&2
  exit $err
end



# ### mean
sudo npm install -g mean-cli
or begin
  set -l err $status
  echo "Error: Failure installing $PROG_NAME"
  echo "Error: npm failed to install $PROG_NAME" >&2
  exit $err
end



# ## Complete
echo "
Installation complete, and $PROG_NAME is now available.

To create a project:

    \$ mean init <myApp>
    \$ cd <myApp> && npm install

"


end
main
# vim: set filetype=fish:
